server:
  port: 8080
spring:
  application:
    name: exam-system-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/exam_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动映射 (如 create_time -> createTime)
    log-impl: ${MYBATIS_LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
